name: Custom Action

on:
  push:
    branches:
      - main  # Trigger action on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f1002833@ds.study.iitm.ac.in
        run: echo "Hello, world!" # Your specific command
